name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Prepare deployment
        run: |
          # Создаем директорию для деплоя
          mkdir -p deploy
          # Копируем все файлы из build/demo
          cp -r build/demo/* deploy/
          # Копируем _headers файл
          cp demo/_headers deploy/
          # Создаем index.html, который будет перенаправлять на camera_positions.html
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=camera_positions.html"></head></html>' > deploy/index.html
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy 